services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    image: app:portifolio-website
    container_name: portifolio-website
    command: >
      sh -c "until mysqladmin ping -h db --silent; do sleep 2; done &&
          python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db_data:/var/lib/mysql