# Generated by Django 5.2 on 2025-06-08 03:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=19, null=True, validators=[django.core.validators.RegexValidator(message='Type between 10 and 15 digits.', regex='^\\d{10,15}$')])),
                ('subject', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('email_send', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': "Email's",
            },
        ),
    ]
