# Generated by Django 5.2 on 2025-06-03 16:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMeEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Ex: 5511999998888 (cód. país + DDD + número)', max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='Digite apenas os números: código do país + DDD + número (ex: 5511999998888)', regex='^\\d{12,13}$')])),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': "Email's",
            },
        ),
    ]
