# Generated by Django 5.2 on 2025-06-03 23:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_contactmeemail_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmeemail',
            name='phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Digite apenas os números: código do país + DDD + número (ex: 5511999998888)', regex='^\\d{12,13}$')]),
        ),
    ]
