# Generated by Django 5.2 on 2025-06-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_contactmeemail_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmeemail',
            name='subject',
            field=models.CharField(default='BR', max_length=160),
            preserve_default=False,
        ),
    ]
