# Generated by Django 5.2 on 2025-06-05 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_contactmeemail_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmeemail',
            old_name='text',
            new_name='message',
        ),
    ]
