# Generated by Django 5.2 on 2025-06-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_text_contactmeemail_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmeemail',
            name='email_send',
            field=models.BooleanField(default=True),
        ),
    ]
