# Generated by Django 5.2 on 2025-06-05 23:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_contactmeemail_email_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmeemail',
            name='email_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contactmeemail',
            name='phone',
            field=models.CharField(blank=True, max_length=19, null=True, validators=[django.core.validators.RegexValidator(message='Digite apenas os números: código do país + DDD + número (ex: 5511999998888)', regex='^\\d{12,13}$')]),
        ),
    ]
