# Generated by Django 5.2 on 2025-06-06 14:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_contactmeemail_email_send_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmeemail',
            name='phone',
            field=models.CharField(blank=True, max_length=19, null=True, validators=[django.core.validators.RegexValidator(message='Type between 10 and 15 digits.', regex='^\\d{10,15}$')]),
        ),
    ]
