# Generated by Django 5.2 on 2025-05-31 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short_desc', models.TextField(max_length=200)),
                ('long_desc', models.TextField(blank=True, null=True)),
                ('img_icon', models.ImageField(blank=True, null=True, upload_to='tag_icon/%Y-%m/')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tag',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short_desc', models.TextField(max_length=400)),
                ('long_desc', models.TextField(blank=True, null=True)),
                ('img_icon', models.ImageField(blank=True, null=True, upload_to='project_icon/%Y-%m/')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('tags', models.ManyToManyField(blank=True, default='', to='projects_app.tags')),
            ],
        ),
    ]
