# Generated by Django 5.2 on 2025-06-01 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='img_icon',
            field=models.ImageField(blank=True, null=True, upload_to='project'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='img_icon',
            field=models.ImageField(blank=True, null=True, upload_to='tag'),
        ),
    ]
