# Generated by Django 5.2 on 2025-06-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0003_alter_project_created_at_alter_tags_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
    ]
