# Generated by Django 5.2 on 2025-06-03 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0004_project_favorite_project_visibility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='favorite',
            new_name='featured',
        ),
    ]
