# Generated by Django 5.2 on 2025-05-01 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_tags_remove_project_name_project_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tag'},
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.tags'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_desc_project',
            field=models.TextField(blank=True, null=True),
        ),
    ]
