# Generated by Django 5.2 on 2025-05-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_tags_options_project_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='long_desc_project',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_desc_project',
            field=models.TextField(max_length=400),
        ),
    ]
