# Generated by Django 5.2 on 2025-05-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_project_created_at_alter_project_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='long_desc_project',
            new_name='project_long_desc',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='short_desc_project',
            new_name='project_short_desc',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='tags',
            new_name='project_tags',
        ),
        migrations.AddField(
            model_name='project',
            name='project_slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='tags',
            name='tag_slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
