# Generated by Django 5.2 on 2025-05-05 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_rename_long_desc_project_project_project_long_desc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_long_desc',
            new_name='long_desc',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_short_desc',
            new_name='short_desc',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_tags',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='tags',
            old_name='tag_desc_long',
            new_name='_desc_long',
        ),
        migrations.RenameField(
            model_name='tags',
            old_name='tag_desc_short',
            new_name='desc_short',
        ),
        migrations.RenameField(
            model_name='tags',
            old_name='tag_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tags',
            old_name='tag_slug',
            new_name='slug',
        ),
    ]
