# Generated by Django 5.2 on 2025-05-05 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_rename_project_long_desc_project_long_desc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='_desc_long',
            new_name='desc_long',
        ),
    ]
