# Generated by Django 5.2 on 2025-05-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_rename__desc_long_tags_desc_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='img_icon',
            field=models.ImageField(blank=True, null=True, upload_to='tag_icon/%Y%m/'),
        ),
    ]
