# Generated by Django 5.2 on 2025-05-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_tags_img_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='img_icon',
            field=models.ImageField(blank=True, null=True, upload_to='tag_icon/%Y-%m/'),
        ),
    ]
