# Generated by Django 5.2 on 2025-05-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_alter_tags_img_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='img_icon',
            field=models.ImageField(blank=True, null=True, upload_to='project_icon/%Y-%m/'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='img_icon',
            field=models.ImageField(blank=True, null=True, upload_to='tag_icon/%Y-%m/'),
        ),
    ]
