# Generated by Django 5.2 on 2025-05-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_project_img_icon_alter_tags_img_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
