# Generated by Django 5.2 on 2025-05-21 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_alter_project_created_at_alter_tags_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='desc_long',
            new_name='long_desc',
        ),
        migrations.RenameField(
            model_name='tags',
            old_name='desc_short',
            new_name='short_desc',
        ),
    ]
